# Generated by Django 5.2.4 on 2025-07-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_doc_uid_alter_document_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
